#!/bin/sh

# Generate config.js
cat <<EOF > /usr/share/nginx/html/config.js
window._env_ = {
  REACT_APP_ARRANGER_API_URL: "$REACT_APP_ARRANGER_API_URL",
  REACT_APP_ARRANGER_PROJECT_ID: "$REACT_APP_ARRANGER_PROJECT_ID",
  REACT_APP_KC_AUTH_SERVER_URL: "$REACT_APP_KC_AUTH_SERVER_URL",
  REACT_APP_KC_CLIENT_ID: "$REACT_APP_KC_CLIENT_ID",
  REACT_APP_KC_REALM: "$REACT_APP_KC_REALM",
  SASS_PATH: "$SASS_PATH",
  REACT_APP_USERS_API_URL: "$REACT_APP_USERS_API_URL",
  REACT_APP_CQDG_WEB_APP: "$REACT_APP_CQDG_WEB_APP",
  REACT_APP_CQDG_WEB_SITE: "$REACT_APP_CQDG_WEB_SITE",
  REACT_APP_CQDG_DOCUMENTATION: "$REACT_APP_CQDG_DOCUMENTATION",
  REACT_APP_USER_SNAP_API_KEY: "$REACT_APP_USER_SNAP_API_KEY",
  REACT_APP_REPORTS_API_URL: "$REACT_APP_REPORTS_API_URL"
};
EOF

# Start Nginx
nginx -g "daemon off;"
