/// <reference types="cypress"/>
import '../../support/commands';

beforeEach(() => {
  cy.login();
  cy.visitFileEntity('FI0000981');
});

describe('Page d\'un fichier - Valider les liens disponibles', () => {
  it('Lien DataExploration du panneau Participants-Samples', () => {
    cy.get('[id="biospecimens"] a[class*="EntityTableRedirectLink"]').clickAndWait({force: true});
    cy.get('[data-cy="ProTable_Participants"]').should('exist');
    cy.get('[class*="QueryBar_selected"] [class*="QueryPill_field"]').contains('File ID').should('exist');
    cy.get('[class*="QueryBar_selected"] [class*="QueryValues_value"]').contains('FI0000981').should('exist');
  });

  it('Lien Participant du panneau Participants-Samples', () => {
    cy.get('[id="biospecimens"] td[class="ant-table-cell"]').eq(0).find('[href]').clickAndWait({force: true});
    cy.get('[id="participant-entity-page"]').should('exist');
    cy.get('[class*="EntityTitle"]').contains('PT0000458');
  });

  it('Lien Study du panneau Participants-Samples', () => {
    cy.get('[id="biospecimens"] td[class="ant-table-cell"]').eq(1).find('[href]').clickAndWait({force: true});
    cy.get('[id="study-entity-page"]').should('exist');
    cy.get('[class*="EntityTitle"]').contains('Developmental and epileptic encephalopathies');
  });

  it('Lien NCIT du Sample Type du panneau Participants-Samples', () => {
    cy.get('[id="biospecimens"] td[class="ant-table-cell"]').eq(3).find('[href]')
      .should('have.attr', 'href', 'http://purl.obolibrary.org/obo/NCIT_C449');
  });

  it('Lien NCIT du Tissue du panneau Participants-Samples', () => {
    cy.get('[id="biospecimens"] td[class="ant-table-cell"]').eq(5).find('[href]')
      .should('have.attr', 'href', 'http://purl.obolibrary.org/obo/NCIT_C12434');
  });

  it('Lien DataExploration du panneau Files Generated by the Analysis', () => {
    cy.get('[id="analysis_files"] a[class*="EntityTableRedirectLink"]').clickAndWait({force: true});
    cy.get('[data-cy="ProTable_DataFiles"]').should('exist');
    cy.get('[class*="QueryBar_selected"] [class*="QueryPill_field"]').contains('Analysis ID').should('exist');
    cy.get('[class*="QueryBar_selected"] [class*="QueryValues_value"]').contains('AN0000934').should('exist');
  });

  it('Lien File du panneau Files Generated by the Analysis', () => {
    cy.get('[id="analysis_files"] [data-cy="Link_File_FI0001222"]').clickAndWait({force: true});
    cy.get('[id="file-entity-page"]').should('exist');
    cy.get('[class*="EntityTitle"]').contains('FI0001222');
  });
});
