/// <reference types="Cypress" />
import '../../support/commands';

describe('Page Logout', () => {

  beforeEach(() => {
    cy.login();
    cy.visit('/');
  });

  it('Vérifier les informations affichées', () => {
    cy.logout();

    cy.contains('Available Data').should('exist');
    cy.get('[data-cy="DataRelease_Study"]').contains(/\d{1}/).should('exist');
    cy.get('[data-cy="DataRelease_Study"]').contains('Stud').should('exist');
    cy.get('[data-cy="DataRelease_Participant"]').contains(/\d{1}/).should('exist');
    cy.get('[data-cy="DataRelease_Participant"]').contains('Participants').should('exist');
    cy.get('[data-cy="DataRelease_Biospecimen"]').contains(/\d{1}/).should('exist');
    cy.get('[data-cy="DataRelease_Biospecimen"]').contains('Biospecimens').should('exist');
    cy.get('[data-cy="DataRelease_File"]').contains(/\d{1}B/).should('exist');
    cy.get('[data-cy="DataRelease_File"]').contains('Files').should('exist');

    cy.contains('Data Portal').should('exist');
    cy.contains('The Quebec Center for Genomic Data is a platform for the harmonization and dissemination of genomic data generated by clinical and research studies in Quebec.').should('exist');
    cy.get('[data-cy="Login"]').contains('Login').should('exist');
    cy.get('[data-cy="Signup"]').contains('Sign up').should('exist');
  });
});
