/// <reference types="cypress"/>
import { getDateTime, oneMinute } from '../../support/utils';

const { strDate } = getDateTime();

beforeEach(() => {
  cy.removeFilesFromFolder(Cypress.config('downloadsFolder'));
  cy.login();
  cy.visitFileEntity('FI0000981');
  cy.resetColumns('analysis_files');
  cy.clickAndIntercept('div[id="content"] svg[data-icon="download"]', 'POST', '**/download', 1, 4);
  cy.waitUntilFile(oneMinute);
});

describe('Page d\'un fichier - Exporter le tableau Files Generated by the Analysis en TSV', () => {  
  it('Valider le nom du fichier [CQDG-333]', () => {
    cy.validateFileName('cqdg-files-table-'+`${strDate.slice(0, 4)}-${strDate.slice(4, 6)}-${strDate.slice(6, 8)}`+'.tsv');
  });

  it('Valider les en-têtes du fichier [CQDG-333]', () => {
    cy.validateFileHeaders('ExportTableauFilesPageFile.json');
  });

  it('Valider le contenu du fichier [CQDG-333]', () => {
    cy.validateFileContent('ExportTableauFilesPageFile.json');
  });
});
